insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "1 hr after Breakfast")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "1 hr before dinner")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "2 hrs after 75g Glucose")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "2 hrs after Breakfast")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "2 hrs after Dinner")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "2 hrs after Meal")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "2 hrs after Prandial")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "2 hrs after lunch")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "2 hrs before Dinner")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "2 hrs before lunch")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "ACR (Albumin Creatinine Ratio)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "ACTH")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "ADA (Adenosine Deaminase)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "AG Ratio")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "ANA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Acid Phosphate")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Albumin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Alkaline Phosphatase (ALP)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Ammonia")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Amylase")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Apo B + Apo A1 & Ratio")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "BNP(Brain or B- type Natriuretic Peptide)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "BUN")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Beta2-Microglobulin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Bicarbonate (HCO3)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "CCR")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "CK-MB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "CPK")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Calcium")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Ceruloplasmin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Cholesterol (Total)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Copper (CU)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Cystatin C")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Erythropoietin (EPO)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Fasting (FBS)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Ferritine")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Folate")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Folic Acid")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "GTT")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "GTT(1 Hr 50 gm Glucose)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Gamma GT")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Globulin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "HBA1C")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "HDL Cholesterol")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Homocystein")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Ing. Phosphate (PO4)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Iron")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Iron Profile (Iron+TIBC+Ferri)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "LDL Cholesterol")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Lactate")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Lipid Profile (Fasting)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Lipid Profile (Random)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Liver Function Test(Bill-Total+Alt+Alk)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Na+,K+,CL")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "OGTT (100gm Glucose (1hr, 2hr,3hr)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "OGTT (75gm Glucose (FBS,1hr, 2hr)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Pleural Fluid")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Potassium (K+)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Procalcitonin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Protein C")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Protein S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Protein Total & A/G ratio")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Random (RBS)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Renal Function Test(creat+Urea+Uric Acid+ELC+U-RE)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Albumin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Amenia")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Amylase")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Bilirubin (Direct)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Bilirubin (Indirect)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Bilirubin (Total)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Bilirubin (Total+Direct+Indirect)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Calcium")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Cortisol Level")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Creatinine")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Electrolytes")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Inorganic Phosphate (PO4)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. LDH")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Lipase")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Lithium")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Magnesium")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Osmolality")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Phosphate")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Total Acid Phosphate")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Uric Acid")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "S. Vit B12")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "SGOT (AST)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "SGPT (ALT)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Sodium (Na+)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "TCO2")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "TIBC")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "TROPONIN - I")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Total Protein")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Transferring")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Triglycerides(TG)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "UBT- (Urea Breath Test)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "UTV (Urine Total Volume)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urea")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Amylase")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Calcium")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Copper")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Creatinine")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Creatinine Clearance Rate (CCR)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Inorganic Phospate")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Magnesium")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Micro Albumin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary NGAL")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Osmolality")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Potassium (K)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Sodium (Na)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Total Protein 24hr (UTP)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Urea")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urinary Uric Acid")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Urine for PCR")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Vit B12")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Vitamin D-(25-OH)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "Von Willebrand Factor Assay (VWF)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BIOCHEMISTRY", "e-GFR")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BLOOD_GROUPING", "Blood Group & Rh Factor")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "BLOOD_GROUPING", "aaa")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "ACR")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Bence - Jone's Protein")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Bence-Jones Protein")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Bile Pigments")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Bile Salts")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Stool  Reducing Substance")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Stool OBT")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Stool R/E")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Stool R/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urine Albumin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urine Ketone Bodies")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urine R/E")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urine Sugar")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urine for AFB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urine for Benzodiazepines")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urine for Gram Stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urine for Haemoglobin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urine for Pregnancy test")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urine for Specific Gravity")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urine for pH")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CLINICAL_PATHOLOGY", "Urobilinogen")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CTG", "CTG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CYTOPATHOLOGY", "FNAC")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CYTOPATHOLOGY", "FNAC (CT Guided)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "CYTOPATHOLOGY", "FNAC (Ultrasound Guided)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DIALYSIS", "Dialysis")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Alcohol (Ethanol)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Amphetamine")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Barbituate")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Benzodiazepines")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Cannabinoids")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Carbamazepine")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Cocaine")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Cyclosporine")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Digoxin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Gentamicin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Opiates")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Phencyclidin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Phenobarbital")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Phenytoin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Salicylate")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Tacrolimus")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Theophyline")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Valporic Acid")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUGS_MONITORING", "Vancomycin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "DRUG_EXAM", "Body Fluid Examination(Ascit/Pleural/Paritoneal)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ECG", "Doppler Echo & Color Flow Imaging")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ECG", "ECG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ECG", "ECG-12 Lead")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ECG", "ECHO Portable")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ECG", "ETT-Treadmill Stress ECG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ECG", "Echo (Color Doppler)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ECG", "Echo 2D & M-Mode")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Anti CCP")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Anti Cardiolipin IgG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Anti Cardiolipin IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Anti DNA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Anti Phospholipid Antibody")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Anti Thyroglobulin Anti body")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Anti Thyroid Anti body")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Anti-Mullerian Hormone (AMH)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "C-ANCA (Anti PR-3)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "C-Peptide")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Cortisol")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Cortisol (Afternoon)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Cortisol (Morning)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "DHEA-S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Estrodiol")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Estrogen")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "FSH")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Free PSA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Free T3")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Free T4")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Free Testosterone")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Growth Hormone")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "HDV Ab")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Inhibin A")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Insulin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "LH")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Myoglobin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Oestrogen")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "P-ANCA (Anti MPO)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Para Thyroid Hormone (PTH)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "ProGRP")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Progesterone")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Prolactin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "S. Basal Cortisol")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "SCC-Ag")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "T-Uptake")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "T3")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "T4")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "TSH")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Testosterone")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Thyroglobulin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Trepnonema Pallidum [TP]")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Triple Pregnancy Screaning(AFP+eU3+HCG)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Ultrasensitive hGH")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "ENDOCRINOLOGY", "Unconjugated Estriol (uE3)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "APTT")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Anti Thrombin (III)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "BT")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Blood Film (PBF)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Bone Marrow Examination")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "CBC")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "CBC with Blood Film (PBF)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "CBC with ESR")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "CBC, BT, CT")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "CT")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Cir. Eosinophil Count")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Cogulation Factor (IX)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Cogulation Factor (VIII)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Coombs Test")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "DC")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "ESR")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Fibrinogen")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "HCT/ PCV")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Haemoglobin Electrophoresis")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Hb%")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Hb% & ESR")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Hb% & HCT")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "ICT for Kala-Azar")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Lupus Anti Coagulation (LA) Confirmation")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Malarial Parasite")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Platelet count")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Prothrombin Time (INR)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "RBC Parameters")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Reticulocyte count")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Rh Antibody Titre")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "Sputum Eosinophil")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "TC")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "TC, DC")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HAEMATOLOGY", "TC, DC, Hb, ESR Combined")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HISTOPATHOLOGY", "Forzen Section Per Slice")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HISTOPATHOLOGY", "Histopathology Intermediate")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HISTOPATHOLOGY", "Histopathology Large")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HISTOPATHOLOGY", "Histopathology Small")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HISTOPATHOLOGY", "Slide Review For Histopathology")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "HOSPITAL", "Consultation Fee")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Alpha Feto Protein (AFP)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Anti Phospholipid Antibody(IgG&IgM)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Anti TB IgG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Anti TB IgG, IgA, IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Anti TB IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Anti TP Strip Test (Syphilis)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Anti Tpo(Anti-Thy.per.Ab)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Anti-TB IgA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Antibody HSV IgG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Antibody HSV IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "CA-125")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "CFT for Filaria")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "CFT for Kala-Azar")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Complement (C3)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Gene Xpert MTB/RIF")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "ICT for Malaria")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "ICT for TB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "IgM  for Rubela")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Mantoux Test (MT)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "Normal test")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "S. IgA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "S. IgE")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "S. IgG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "IMMUNOLOGY", "S. IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Blood C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "C/S (For Mehtod)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "CSF For AFB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "CSF For Analysis")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "CSF For Bacterial")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "CSF For C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "CSF R/E")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "CSF Study for")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Clot Culture (salmonella inf.)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Conjunctival swab C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Endocervical swab C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Endocervical swab for gram stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Eye swab C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "FNAC")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "FNAC Collection")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Finger Print for C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Gastric Level aspirate (3 Sample)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Gram stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "HVS C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "HVS for Gram Stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "HVS for R/E")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Miscellaneous Iteam For AFB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Miscellaneous Iteam For C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Miscellaneous Iteam For Cytology")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Miscellaneous Iteam For Fungul Stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Miscellaneous Iteam For Gram Stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Miscellaneous Iteam For Malignant Cells")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Nasal swab C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "PAPS C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Prostatic smear C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Prostatic smear R/E")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Prostatic smear gram stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Pus C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Pus For AFB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Pus For Gram Stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Skin Scraping   R/E")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Skin Scraping for C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Skin Scraping for Fungus")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Skin Scrapping C/S for Fungus")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Skin Scrapping For Gram Stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Sputum AFB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Sputum AFB 2 samples")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Sputum AFB 3 samples")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Sputum C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Sputum For Eosiphil")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Sputum for Gram Stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Sputun - AFB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Stool C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Stool For AFB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Stool For Rota Virus")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Swab C/S with Gram Stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "T/A For C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "T/A for ABF Staining")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Throat Swab C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Throat Swab For AFB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Throat Swab For C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Throat Swab For Gram Stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Throat Swab For KLB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Umbilical swab C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Urethra smear C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Urethra smear R/E")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Urethral Discharge For C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Urine C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Urothral for Gram  Stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Wound Swab For AFB")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Wound Swab For Gram Stain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "MICROBIOLOGY", "Wound swab C/S")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Ap Toral In OT")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Blood Collection Bag")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Collection")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Cytomegalo Virus (CMV)-IgG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Cytomegalo Virus (CMV)-IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "D-Dimer")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Enima Charge")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "FDP")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "HSV 1 (IgG&IgM)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "HSV 1&2 (IgG&IgM)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "HSV 2 (IgG&IgM)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "ICT for Chlamydia")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "ICT for Dengue Antibody (IgG & IgM)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "ICT for Filaria")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Iv Canula")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Operation Charge")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Operation Charge")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Pulse Oximeter")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "RBS By Glucometer")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "RBS By Glucometer")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Rapid Test for Influenza A &B")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Rubella - IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Rubella- IgG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Semen Analysis")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Suture Materials")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "T-tube Cholangiography")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Torch Panel")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Toxo-IgG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "OTHERS", "Toxo-IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "ANF/ANA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "ASO Titre")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "Anti Dengue IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "Anti- HIV (1+2)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "Blood Cross Matching")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "Blood Cross Matching with Screening")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "CRP")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "Complement (C4)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "Dengue NS1 Ag")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "EBV-VCA IgG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "EBV-VCA IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "Febrile Antigen")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "H.Pylori Antibody")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "HBsAg ELISA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "HCG/PT")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "RA Test")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "RF")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "Rose-Waaler test")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "TPHA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "Torch Anti Body")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "VDRL")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "VDRL (Q+Q)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "SEROLOGY_IMMUNOLOGY", "Widal Test")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "T", "Urine for Amphetamine")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "T", "Urine for Barbiturate")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "T", "Urine for Benzodiazepines")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "T", "Urine for Cannabinoids")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "T", "Urine for Cocaine")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "T", "Urine for Marijuana/Canabiniods")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "T", "Urine for Morphine/Heroin/Opiates")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "T", "Urine for Opiates")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "T", "Urine for Phencyclidin")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Anti CCP")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Anti Cardiolipin Antibody")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Anti Cardiolipin IgG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Anti Cardiolipin IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Anti Mitocondrial Antibody")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Brucella Agglulination Test")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "CA-125")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "CA-15.3")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "CA-19.9")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "CEA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Chikungunya IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Cytology")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Free PSA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Free PSA/Total PSA Ratio")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Intrinsic Factor Ab")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Monosport Test")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "PSA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "PSA Profile")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "Pap smear")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "TUMOR_MARKER", "hs CRP")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Brain")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "HBS")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "HBS - Upper Abdomen")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "KUB Female")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "KUB Male")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "L/S Spine A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "L/S Spine B/Oblique view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "L/S Spine B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "L/S Spine Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Lower Abdomen")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Lower abdomen Female")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Lower abdomen Male")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Molar Pregnancy")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Pregnancy")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Pregnancy Profile with Anomaly Scan (4D)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Reproductive organ Female")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Transvaginal sonography")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "USG Head")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "USG Testis")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "USG Thyroid")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "USG both Breast")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "USG for Pregnancy (4D)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "USG of Inguinl Region")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "USG of Left Arm")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "USG of Right Arm")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "USG of Scrotum/Testis")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Upper abdomen Female")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Upper abdomen Male")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "WA Early Pregnancy")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "WA with pregnancy")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Whole Abdomen & Pelvis")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Whole abdomen Female")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "USG", "Whole abdomen Male")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "ABG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Anti DS DNA")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Anti H. pylori IgG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Anti HAV IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Anti HBc (Total)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Anti HBc IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Anti HBe")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Anti HBs")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Anti HCV")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Anti HEV IgG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Anti HEV IgM")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Beta HCG")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Biopsy")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "HBV-DNA (PCR)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "HBe Ag")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "HBs Ag")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "HCVNA (PCR)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "HIV- 1&2")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "S. Testosteron")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "S.Basal Testosteron")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "VIROLOGY", "Triglycerides")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Abdomen AP")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Abdomen E/P adult")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Abdomen E/P child")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Atlas  bone A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Atlas  bone B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "BA ENAMA D/C")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "BA Follow Through")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "BA MEAL S/D")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "BA-Enema of Large GUT")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Ba-Enema let film one")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Ba-Follow through let film three")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Ba-Swallow and Follow through")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Ba-Swallow of oesophagus")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Ba-follow through let film one")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Ba-follow through let film two")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Bone Age L-1")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Bone Age L-2")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Bone Age L-3")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both Knee Joint A/P")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both Knee Joint A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both Knee Joint B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both Knee Joint B/VView")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both Knee jt A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both Mandible AP/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both Mastoid Townes  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both clavicle A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both clavicle A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both hib joint")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both hip A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both mastoid townes  view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Both orbit P/A View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Cervical Spine A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Cervical Spine B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Cervical Spine Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Cervical spine flexion and extension")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest A/P  Lateral View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest A/P  Lateral View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest A/P Supine")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest A/P for Ribs")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest Lt Lateral View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest Lt Posterior obique (LPO)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest Lt anterior oblique (LAO)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest P/A  Lateral Decubitus View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest P/A  Lateral Decubitus View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest P/A  Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest P/A  Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest P/A (Inspiration )")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Chest P/A View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Dental one film")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Dental three film")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Dental two film")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Dorsal  Spine B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Dorsal Spine A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Dorsal Spine Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Dorso Lumber Spine")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Dorso-Lumber A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Dorso-Lumber B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Dorso-Lumber Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Elbow with fore arm  B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Face B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Face Lateral View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Face P/A View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "IVU")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "IVU Let film one")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "IVU Let film two")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "IVU/IVP")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "KUB A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "KUB B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "KUB adult 100%")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "KUB child 100%")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "KUB errect")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "KUB x-ray")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Kub with lower abdomen Female")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Kub with lower abdomen Male")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "L/S Spine Flexion")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "L/S spine flexion and extension")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Ankle jt B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Fore Arm B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Hand B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Heel B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Hip B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Knee A/P  Standing View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Knee jt A/P")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Knee jt B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Leg B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Little finger B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Mastoid  Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Mastoid Stenverse  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Mastoid Stenverse view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Mastoid Townes  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Middle finger B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Neck of Femur A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Neck of Femur B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Patella P/A")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Patella Skyline  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Patella Skyline view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Ring  finger B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Scaphoid  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Scapula A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Scapula B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Shouder jt  Swimmers View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Shouder jt A/P  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Sole B/V View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Sub-Mandibular gland Lateral oblique View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt TM jt open  mouth")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Thigh B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Wrist jt B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt Zygomatic bone B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt ankle and foot B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt arm B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt calcaneum Axial view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt calcaneum B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt cavicle B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt clavicle A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt elbow jt B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt foot B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt great toe B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt index B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt knee jt tunnel view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt orbit  oblique View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt orbit B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt shoulder jt  B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt shoulder jt  internal  rotation")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt shoulder jt A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt thumb B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lt wrist jt  B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "LtFemur Including Hip A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "LtFemur Including Hip B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lumber Spine A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lumber Spine B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Lumber Spine Lateral View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Mandible B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Mandible Lateral View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Mandible Lateral oblique view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Mandible P/A view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Mastoid townes view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Maxilla  B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Maxilla Lateral  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Maxilla Lateral oblique view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Maxilla P/A view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Nasal bone B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Nasal bone lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Nasopharynx  Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Neck A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Neck B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Neck Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "PNS B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "PNS Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "PNS OM view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "PNS Occipito-Frontal view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Pancreas A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Pelvimetry A/P  (Errect)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Pelvis A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Pelvis B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Pelvis Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Plain Abdomen in E/P")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Plain Abdomen in E/P Child")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "RGU + MCU")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "RT Foot  B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Retrograde Cysto-Urethrogram (RCU)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Retrograde Cysto-Urethrogram with MCU")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Retrograde Urethrogram (RGU)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt  Mastoid Stenverse  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt  Shoulder jt A/P  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Ankle jt B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Ankle jt B/V(Digital)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Femur Including Hip A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Fore Arm B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Heel B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Hip A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Hip B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Knee A/P  Standing View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Knee jt B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Leg B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Little finger B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Mastoid  Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Mastoid  Stenverse view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Mastoid Townes  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Middle finger B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Neck of Femur A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Neck of Femur B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Patella P/A")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Patella Skyline  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Patella Skyline view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Ring finger B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Scaphoid  View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Scapula A/P View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Scapula B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Shoulder jt Swimmers View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Sole B/V View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Sub-Mandibular gland Lateral oblique view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt T/F")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt TM jt open  mouth")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt Zygomatic bone B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt ankle and foot B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt arm B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt calcaneum Axial view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt calcaneum B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt clavicle A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt elbow jt B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt foot B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt fore arm B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt great toe B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt hand B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt index B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt knee jt Tunnel view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt orbit B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt orbit oblique View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt shoulder jt  B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt shoulder jt  internal  rotation")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt shoulder jt A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt thumb B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt wrist jt  B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt. Thigh B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Rt.Wrist B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sacro-coccygeal A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sacro-coccygeal B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sacro-coccygeal Lateral")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sella-Turcica Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sialogram of Lt Parotid gland")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sialogram of Lt Sub-Mandibular gland")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sialogram of Rt Sub-Mandibular gland")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sialogram of Rt parotid gland")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Skull A/P  Lateral View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Skull A/P view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Skull B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Skull Fronto-occipital view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Skull Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Skull P/A view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Skull SM view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Spine A/P View (child)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Spine B/V (child)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Spine Lateral View (child)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sterno-clavicular jt P/A View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sternum A/P")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sternum A/P  view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sternum Lateral view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Sternum oblique view")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Styloid Proces B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Throat B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Throat Lateral View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Throat P/A View")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "Throsis Spine B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "X-ray Cervical Spine B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "X-ray L/S Spine B/V")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "X-ray(Portable indor)")
insert into `lab_test`(`ID`, `GROUP`, `NAME`) VALUES (null, "X-RAY", "X-ray(portable ICU)")
